### ISSUE TITLE
open mouth

### ISSUE THREAD

**Issue by fnhdx** [TadasBaltrusaitis/CLM-framework#51]
I found an issue when I opened my mouth widely. The landmarks of lower lip are always moved up to my teeth. Do you think it is due to the training or  the regularisation term?
In your code, when do NU_RLMS on local parameters, two regularisation term are added.
1.
J_w_t_m(Rect(0,6,1, m)) = J_w_t_m(Rect(0,6,1, m)) - regTerm(Rect(6,6, m, m)) * current_local;

2.
Hessian = Hessian + regTerm;

I understand the second one which is Tikhonov regularisation. But what is the first term? I even checked the Saragih 2011 paper, it's not very clear where the first regularisation term is from?

I tried to remove the first term, it looks like the result is better for the open mouth case. Do you have any idea about it? Thanks a lot.

**Comment by TadasBaltrusaitis** [comment]
CLM framework is quite out of date now, you should have a look at OpenFace project - https://github.com/TadasBaltrusaitis/OpenFace, which is the continuation of CLM work but with greater functionality and more accurate models, which should address the mouth opening issue (at least partally). The cause is both the training and regularization: 1) the training data does not contain many examples of widely open mouths, 2) open mouth is an unlikely face so regularization penalizes its likelihood.

For a more detail of the terms of the regularization you can have a look at my thesis - https://www.dropbox.com/s/gk6nlgn4y9vcm4d/TechReport.pdf?dl=0, specifically section 4.5.2 which explains where all the terms come from (this is actually what encourages the model to stay close to "neutral" faces)

**Comment by fnhdx** [comment]
Thanks for your reply. I agree with you. 
 I did check the Openface project. My understanding is Openface framework is similar to ccnf with better patch expert. but the global regularization (PDM) is same as ccnf. A

**Comment by TadasBaltrusaitis** [comment]
You are right that it uses the same PDM, however, as the patch experts are more reliable, the regularization on the PDM can be reduced somewhat, allowing for more "unusual" expressions.

**Comment by fnhdx** [comment]
thanks a lot for your answers.
