### ISSUE TITLE
tri_68.mat file.

### ISSUE THREAD

**Issue by saamishon** [TadasBaltrusaitis/CLM-framework#6]
can you please tell how to produce /matlab_version/pdm_generation/tri_68.mat file?

**Comment by TadasBaltrusaitis** [comment]
It was created using a Delaunay triangulation (Matlab has a function to do this) of landmark points of the mean shape from the automatically constructed PDM (using only the X and Y components). The result was later manually post-processed to cut out mouth and eye regions. Hope this answers your question. Let me know if you have any more questions, but possibly the best way to do this is by e-mailing me rather than raising an issue, as this is not really a problem or a bug with the code.

**Comment by saamishon** [comment]
Right. Many thanks.

**Comment by XterNalz** [comment]
What is the rationale behind cutting out the mouth and eye regions?

**Comment by TadasBaltrusaitis** [comment]
The reason is to make avatar animation or expression transfer easier, for example for projects like this - http://www.cl.cam.ac.uk/~tb346/pub/papers/idgei2014.pdf, and is used more in the FAME branch of the code.

It doesn't have much bearing on landmark detection, but for simplicity the same triangulation is used in face validation stage.
